name: Compile yaota8266.bin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'init'
      run: |
        make update
        make rsa-keys

    - name: 'compile yaota8266.bin'
      run: |
        make build
        ls -la yaota8266/
        file yaota8266/yaota8266.bin
        make verify
